<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="MYSHEC544566L" failures="2" tests="3" name="runners.RunnerClass" time="23.970" errors="0" timestamp="2025-06-20T20:47:31 IST" skipped="0">
  <testcase classname="runners.RunnerClass" name="runScenario" time="9.619">
    <failure message="expected:&lt;200&gt; but was:&lt;404&gt;" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<404>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:86)
at stepDefinitions.ValidateBrokenImagesSteps.user_should_get_image(ValidateBrokenImagesSteps.java:47)
at ✽.user should get image(file:///C:/Users/vemula.krishna/eclipse-workspace/ui_automation/src/test/resources/features/vaildateBrokenImages.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runners.RunnerClass" name="runScenario" time="7.516"/>
  <system-out/>
  <testcase classname="runners.RunnerClass" name="runScenario" time="6.835">
    <failure message="expected:&lt;200&gt; but was:&lt;404&gt;" type="junit.framework.AssertionFailedError">
      <![CDATA[junit.framework.AssertionFailedError: expected:<200> but was:<404>
at junit.framework.Assert.fail(Assert.java:57)
at junit.framework.Assert.failNotEquals(Assert.java:329)
at junit.framework.Assert.assertEquals(Assert.java:78)
at junit.framework.Assert.assertEquals(Assert.java:86)
at stepDefinitions.ValidateBrokenImagesSteps.user_should_get_image(ValidateBrokenImagesSteps.java:47)
at ✽.user should get image(file:///C:/Users/vemula.krishna/eclipse-workspace/ui_automation/src/test/resources/features/vaildateBrokenImages.feature:25)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- runners.RunnerClass -->
